# Generated by Django 4.2.4 on 2024-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_eventmodel_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventhead', models.CharField(max_length=20)),
                ('guest1', models.CharField(max_length=20)),
                ('guest2', models.CharField(max_length=20)),
                ('guest3', models.CharField(max_length=20)),
                ('guest4', models.CharField(max_length=20)),
                ('guest5', models.CharField(max_length=20)),
            ],
        ),
    ]
