# Generated by Django 4.2.4 on 2024-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_guestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventhead', models.CharField(max_length=20)),
                ('guest1', models.CharField(max_length=20)),
                ('guest1age', models.IntegerField()),
                ('guest1gender', models.CharField(max_length=10)),
                ('guest2', models.CharField(max_length=20)),
                ('guest2age', models.IntegerField()),
                ('guest2gender', models.CharField(max_length=10)),
                ('guest3', models.CharField(max_length=20)),
                ('guest3age', models.IntegerField()),
                ('guest3gender', models.CharField(max_length=10)),
                ('guest4', models.CharField(max_length=20)),
                ('guest4age', models.IntegerField()),
                ('guest4gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='GuestMOdel',
        ),
    ]
